namespace ConditioningControlPanel.Services.Chaos;

/// <summary>
/// The one tuning block for the hold-to-defuse verb rework and the behavioral bubbles
/// (2026-06-11). Every constant here WILL be rebalanced — keep them named and together,
/// never inline a magic number for any of these in logic code.
/// </summary>
public static class ChaosTuning
{
    // ============================ Focus resource ============================
    // Focus is GENERATED by popping treat-class bubbles and catching white rabbits,
    // and SPENT completing defuse channels. No passive regen, no decay.

    public const double FOCUS_MAX = 100;
    public const double FOCUS_START = 50;

    public const double FOCUS_PER_POP = 10;      // flash, subliminal, any standard treat
    public const double FOCUS_PER_GOLDEN = 12;   // lucky golden bubble
    public const double FOCUS_PER_DROPLET = 4;   // each Gold Digger droplet
    public const double FOCUS_PER_HEART = 10;    // heart catch (on top of +1 resistance)
    public const double FOCUS_PER_RABBIT = 15;   // white rabbit catch
    public const double FOCUS_PER_PRISM = 10;    // prism popped as the treat it mimics
    public const double FOCUS_PER_HEAVY = 15;    // heavy giant (3x pay, slightly more focus)

    // ============================ Defuse channel ============================

    /// <summary>Focus spent per COMPLETED channel (deducted on completion, never on start).</summary>
    public const double DEFUSE_COST = 30;
    /// <summary>Hold this long over a live bubble to deflate it. The fuse pauses meanwhile.</summary>
    public const int DEFUSE_HOLD_MS = 1000;
    /// <summary>Press+release faster than this reads as a CLICK (it still triggers the bubble —
    /// this threshold only picks the click-detonate feedback/bark over the early-release one).</summary>
    public const int CLICK_THRESHOLD_MS = 180;
    /// <summary>Visual shrink floor while channeling (scale 1.0 → this by completion).</summary>
    public const double CHANNEL_MIN_SCALE = 0.55;

    /// <summary>rh_focus_low: seconds of "focus below cost while lives hang on screen" before
    /// the once-per-run warning bark fires.</summary>
    public const double FOCUS_LOW_BARK_SEC = 8;

    // ============================ behavioral bubbles ============================
    // Spawn rolls REPLACE an ordinary spawn slot (field density stays sane). Gating:
    // none on Gentle; Echo + Chaperone from Teasing; Tease from the Slipping rank
    // (10 descents); Bound from Relentless.

    /// <summary>First-ever encounter of each behavioral bubble: it spawns alone (its roll
    /// consumes the whole spawn tick) with a gentler, longer trance.</summary>
    public const double DEBUT_FUSE_MULT = 1.5;

    // ---- The Echo: triggers split it into two smaller, faster lives; a held defuse is clean ----
    public const double ECHO_SPAWN_CHANCE = 0.05;
    public const double ECHO_CHILD_SCALE = 0.6;        // children render at this fraction of the parent
    public const double ECHO_CHILD_SPEED_MULT = 1.5;
    public const int ECHO_CHILD_FUSE_MIN_MS = 2500;
    public const int ECHO_CHILD_FUSE_MAX_MS = 3000;

    // ---- Field pace + entry variety (2026-06-11 first-session feedback) ----
    /// <summary>Global chaos bubble speed bump — verticals travel farther before they rot.
    /// (2026-06-12: +15% over the original 1.25 — field felt sluggish.)</summary>
    public const double CHAOS_SPEED_MULT = 1.4375;

    /// <summary>Global simulation pace, &lt;1 = slower. Every per-tick motion step and countdown
    /// (motion <c>_vx*ts</c>, fuse/tease/darter <c>-= 32*ts</c>) routes through Bubble.TimeScale, so
    /// this one knob uniformly slows travel AND lengthens fuses/fades for both ambient and chaos
    /// bubbles. WHY it exists: the animation is fixed-step (each tick assumes a flat 32 ms), so visible
    /// speed tracks how often the 32 ms render-priority timer actually fires. Pre-6.1.6 the UI thread
    /// was heavily loaded (per-bubble SetWindowPos storm, per-spawn text rasterization, DVD windows,
    /// GIF decode spikes), starving that timer — the field ran in unintended slow-motion. The 6.1.6
    /// perf pass removed that load, so the timer now fires at its true ~31 fps and the field snapped to
    /// its (faster) designed pace, which testers read as "everything sped up / bubbles fade too fast".
    /// This restores the prior feel without reverting the perf wins. Dial toward 1.0 for the full
    /// designed pace, toward ~0.6 for the old sluggish feel. The proper long-term fix is real
    /// delta-time (measure elapsed ms per tick); this constant is the deliberate stop-gap.</summary>
    public const double FIELD_PACE = 0.8;

    /// <summary>Hard cap on freeze pickups visible at once. A swarm of freezes let the player
    /// chain near-permanent field holds; two on screen keeps it a scramble, not a guarantee.</summary>
    public const int FREEZE_MAX_ON_SCREEN = 2;
    /// <summary>Chance an ordinary FloatUp/RainDown spawn swaps to drifting in from a side
    /// edge (Mixed motion only; an explicit motion setting is respected).</summary>
    public const double SIDE_DRIFT_CHANCE = 0.30;
    /// <summary>The first few ordinary spawns of a run keep the classic bottom rise —
    /// the side entries land as a surprise after the player has settled in.</summary>
    public const int SIDE_DRIFT_GRACE_SPAWNS = 5;

    // ---- Live fuse ring phases (2026-06-11): YELLOW = burning, time to spare;
    //      YELLOW↔RED flash = act now; SOLID RED = the brink window the danger
    //      power-ups (Last Breath / Slowburner capstone) judge defuses against. ----
    /// <summary>Fuse remaining (ms) at which the ring starts flashing yellow↔red.</summary>
    public const double RING_FLASH_FROM_MS = 2400;
    /// <summary>Fuse remaining (ms) at which the ring goes solid red — kept in step with
    /// the 0.8s brink signal (ChaosLessonHooks.LAST_BREATH_BRINK_SEC / Last Breath max).</summary>
    public const double RING_BRINK_MS = 800;

    // ---- The Chaperone: a live bubble shielded by an orbiting escort treat ----
    public const double CHAPERONE_SPAWN_CHANCE = 0.04;
    // Minimum orbit radius; the effective radius grows with the pair's sizes so the escort
    // always rides OUTSIDE the live's rim (an escort inside the big live is unclickable).
    public const double CHAPERONE_ORBIT_RADIUS_DIP = 80;
    public const double CHAPERONE_ORBIT_GAP_DIP = 18;
    public const double CHAPERONE_ORBIT_PERIOD_SEC = 2.5;

    // ---- The Tease: don't touch it. Any mouse-down triggers it AND halves the streak;
    //      ignoring it to expiry pays the DENIED bonus. Immune to every instant-defuse source. ----
    public const double TEASE_SPAWN_CHANCE = 0.03;
    public const int TEASE_LIFE_MS = 6000;
    public const int TEASE_GOLD_MIN = 5;
    public const int TEASE_GOLD_MAX = 10;
    public const double TEASE_DENIED_SCORE = 120;       // base points for a denial (multipliers apply)
    public const double FOCUS_PER_DENIED = 10;          // restraint feeds focus like a treat would
    public const double TEASE_CENTER_PULL_DIP = 0.55;   // per-frame drift toward its screen's center
    public const int TEASE_DENIED_STREAK_COUNT = 5;     // rh_tease_denied_streak threshold (per run)
    /// <summary>Perf budget: tease bubbles running a REAL animated-gif decode at once; the rest
    /// fall back to a still + shimmer (XamlAnimatedGif decodes native-res frames on the UI thread).</summary>
    public const int TEASE_MAX_ANIMATED = 2;
    public const long TEASE_ANIMATED_MAX_BYTES = 3_000_000;

    // ---- The Brittle: a glass mine — HOVERING over it shatters it and fires a random
    //      live-pool effect (the mimic's ghost reveals underneath, prism-style). It can't
    //      be popped by toys/chains/sweeps; a frozen field is safe to cross. ----
    public const double BRITTLE_SPAWN_CHANCE = 0.035;   // rider roll per ordinary spawn tick (not on Gentle)
    /// <summary>Spawn grace before the glass arms — forgives materialising under the cursor.</summary>
    public const int BRITTLE_ARM_MS = 900;
    public const double BRITTLE_SPEED_MULT = 0.85;      // a slow drifting mine you steer around

    // ---- the Ripple (right-click verb, 2026-06-12): one charge, slow recharge. An expanding
    //      wave from the cursor — treats pop paid, trances snap clean, rabbits get FLUNG
    //      (and a flying rabbit's body mows bubbles). Tease/Brittle/freeze stay cursor-only. ----
    /// <summary>Seconds to gather a fresh charge (the Skipping Stone charm shortens this).</summary>
    public const double RIPPLE_RECHARGE_SEC = 15;
    /// <summary>Unworn wavefront reach (physical px). Each charm level adds RIPPLE_RADIUS_PER_LVL_PX.</summary>
    public const double RIPPLE_RADIUS_PX = 260;
    /// <summary>Unworn expansion time — early ripples are small and quick; charm levels widen
    /// AND slow them (each level adds RIPPLE_LIFE_PER_LVL_MS) so they hang on screen longer.</summary>
    public const double RIPPLE_LIFE_MS = 520;
    public const double RIPPLE_RADIUS_PER_LVL_PX = 45;
    public const double RIPPLE_LIFE_PER_LVL_MS = 110;
    /// <summary>Skipping Stone capstone: gap between the three skipped waves.</summary>
    public const int RIPPLE_WAVE_GAP_MS = 1000;
    /// <summary>A right-click is the game's ONLY when it lands within reach+grace of a chaos
    /// bubble — otherwise it passes through to the desktop (context menus keep working mid-run).</summary>
    public const double RIPPLE_TRIGGER_GRACE_PX = 80;
    /// <summary>Fling: a swept rabbit leaves at its natural darter pace times this (same cap
    /// as fully re-smacked Spanker rabbits).</summary>
    public const double RIPPLE_FLING_SPEED_MULT = 2.2;

    // ---- The Bound: two lives on one elastic tether — both must go, and quickly ----
    public const double BOUND_SPAWN_CHANCE = 0.03;
    /// <summary>The second channel must COMPLETE within this window of the first one
    /// completing, or the survivor enrages. One half triggering enrages the other instantly.</summary>
    public const int BOUND_WINDOW_MS = 2500;
    /// <summary>Per-half defuse cost — the pair totals one normal defuse.</summary>
    public const double DEFUSE_COST_BOUND = 15;
    public const double BOUND_SEPARATION_DIP = 250;
    /// <summary>Enrage: remaining trance halves and speed scales by this.</summary>
    public const double BOUND_ENRAGE_SPEED_MULT = 1.4;
}
